### ISSUE TITLE
What Docker Version?

### ISSUE THREAD

**Issue by rcplane** [NLKNguyen/alpine-mpich#3]
Hello, I am interested in using this project; could you please confirm and document in the readme the recommended versions of Docker and Docker compose?

**Comment by rcplane** [comment]
Sorry, I found them in the cluster readme. https://github.com/NLKNguyen/alpine-mpich/tree/master/cluster

**Comment by NLKNguyen** [comment]
Glad you are interested in using this.  I will put Docker version information in the front page too.

Also, I've just added screencasts in the wiki pages of deployment sections for more clarification.
