### ISSUE TITLE
standard_init_linux.go:195: exec user process caused "exec format error"

### ISSUE THREAD

**Issue by tanweer-ali** [NLKNguyen/alpine-mpich#6]
Hi,

I have a 3-node swarm cluster. 
I am trying to follow the steps to deploy mpi over the swarm. 

After i issue this command: 
./swarm.sh up size=3

I get the following output with the error:

```
===> CLEAN UP CLUSTER

         __v_
        (.___\/{
~^~^~^~^~^~^~^~^~^~^~^~^~
$ docker service rm my-mpi-project-master my-mpi-project-worker

Error: No such service: my-mpi-project-master
Error: No such service: my-mpi-project-worker
=> No problem


===> REMOVE NETWORK

         __v_
        (.___\/{
~^~^~^~^~^~^~^~^~^~^~^~^~
$ docker network rm mpi-network

Error: No such network: mpi-network
=> No problem


===> BUILD IMAGE

         __v_
        (.___\/{
~^~^~^~^~^~^~^~^~^~^~^~^~
$ docker build -t "nlknguyen/mpi" .

Sending build context to Docker daemon  41.47kB
Step 1/3 : FROM nlknguyen/alpine-mpich:onbuild
# Executing 5 build triggers
 ---> Using cache
 ---> Using cache
 ---> Running in f0e72562d307
standard_init_linux.go:195: exec user process caused "exec format error"
The command '/bin/sh -c cat ${SSHDIR}/*.pub >> ${SSHDIR}/authorized_keys' returned a non-zero code: 1

```

**Comment by tanweer-ali** [comment]
Could this be related to my subnet configuration??

My cluster nodes have the following IP addresses: 
192. 168. 1. 104       (manager)
192. 168. 2. 102
192. 168. 2. 103 

How do i configure the subnet for this ??
And the SSH_ADDR is this the IP of the manager node ??

 IMAGE_TAG=nlknguyen/mpi      \                                                                                       
PROJECT_NAME=my-mpi-project  \                                                                                       
NETWORK_NAME=mpi-network     \                                                                                       
NETWORK_SUBNET= ???   \                                                                                       
SSH_ADDR= ???       \                                                                                       
SSH_PORT=2222

**Comment by NLKNguyen** [comment]
Sorry for a very late reply, and you might figured out already. Let me know if you still have the issue.

Btw, IMAGE_TAG should point to your own image location on some registry such as DockerHub. Your current value was pointing to my sample image which you won't be able to push to.

**Comment by NLKNguyen** [comment]
Feel free to reopen the issue if it happens again.
