### ISSUE TITLE
No such file or directory when do mpirun

### ISSUE THREAD

**Issue by KornCode** [NLKNguyen/alpine-mpich#8]
I have placed my mpi file (test.c) in project folder, but this is what happen when I ran the mpirun
[proxy:0:0@069be636be9a] HYDU_create_process (utils/launch/launch.c:75): execvp error on file ./test (No such file or directory)

**Comment by loics2** [comment]
How did you fix this issue?

**Comment by ozturkosu** [comment]
I have faced same problem. Would you please explain how to fix it?

**Comment by gimogo** [comment]
hmmm 2022 now still nothing, same problem
